import type { AnalysisResult } from './skillExtractor';

// New plan format from schema
interface Plan7DaysItem {
  day: number;
  focus: string;
  tasks: string[];
}

// New checklist format from schema
interface ChecklistItem {
  roundTitle: string;
  items: string[];
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}

export function formatPlanAsText(plan: Plan7DaysItem[]): string {
  if (!plan || plan.length === 0) return 'No plan available.';
  return plan.map(day => 
    `Day ${day.day}: ${day.focus}\n` +
    day.tasks.map(task => `  • ${task}`).join('\n')
  ).join('\n\n');
}

export function formatChecklistAsText(checklist: ChecklistItem[]): string {
  if (!checklist || checklist.length === 0) return 'No checklist available.';
  return checklist.map(round =>
    `${round.roundTitle}\n` +
    round.items.map(item => `  □ ${item}`).join('\n')
  ).join('\n\n');
}

export function formatQuestionsAsText(questions: string[]): string {
  return questions.map((q, i) => `${i + 1}. ${q}`).join('\n\n');
}

export function generateFullReport(analysis: AnalysisResult): string {
  const skills = [
    ...analysis.extractedSkills.coreCS,
    ...analysis.extractedSkills.languages,
    ...analysis.extractedSkills.web,
    ...analysis.extractedSkills.data,
    ...analysis.extractedSkills.cloud,
    ...analysis.extractedSkills.testing,
    ...analysis.extractedSkills.other,
  ];

  const confidenceMap = analysis.skillConfidenceMap || {};
  const knownSkills = skills.filter(s => confidenceMap[s] === 'know');
  const practiceSkills = skills.filter(s => confidenceMap[s] !== 'know');
  
  // Use new schema fields with fallbacks
  const plan = analysis.plan7Days || [];
  const checklist = analysis.checklist || [];
  const score = analysis.finalScore ?? analysis.readinessScore ?? 0;

  return `
========================================
PLACEMENT PREPARATION REPORT
========================================

Company: ${analysis.company || 'N/A'}
Role: ${analysis.role || 'N/A'}
Date: ${new Date(analysis.createdAt).toLocaleDateString()}
Readiness Score: ${score}/100
Base Score: ${analysis.baseScore ?? 'N/A'}

----------------------------------------
SKILLS ASSESSMENT
----------------------------------------

Extracted Skills (${skills.length}):
${skills.map(s => `  • ${s} ${confidenceMap[s] === 'know' ? '✓' : '(needs practice)'}`).join('\n')}

Known Skills (${knownSkills.length}):
${knownSkills.length > 0 ? knownSkills.map(s => `  ✓ ${s}`).join('\n') : '  None marked as known'}

Skills Needing Practice (${practiceSkills.length}):
${practiceSkills.length > 0 ? practiceSkills.map(s => `  ○ ${s}`).join('\n') : '  All skills marked as known!'}

----------------------------------------
7-DAY PREPARATION PLAN
----------------------------------------

${formatPlanAsText(plan)}

----------------------------------------
ROUND-WISE CHECKLIST
----------------------------------------

${formatChecklistAsText(checklist)}

----------------------------------------
LIKELY INTERVIEW QUESTIONS
----------------------------------------

${formatQuestionsAsText(analysis.questions)}

----------------------------------------
END OF REPORT
----------------------------------------
Generated by Placement Prep Platform
`.trim();
}

export function downloadAsTxt(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
