import type { AnalysisResult, DayPlan, RoundChecklist } from './skillExtractor';

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}

export function formatPlanAsText(plan: DayPlan[]): string {
  return plan.map(day => 
    `Day ${day.day}: ${day.title}\n` +
    day.tasks.map(task => `  • ${task}`).join('\n')
  ).join('\n\n');
}

export function formatChecklistAsText(checklist: RoundChecklist[]): string {
  return checklist.map(round =>
    `Round ${round.round}: ${round.title}\n` +
    round.items.map(item => `  □ ${item}`).join('\n')
  ).join('\n\n');
}

export function formatQuestionsAsText(questions: string[]): string {
  return questions.map((q, i) => `${i + 1}. ${q}`).join('\n\n');
}

export function generateFullReport(analysis: AnalysisResult): string {
  const skills = [
    ...analysis.extractedSkills.coreCS,
    ...analysis.extractedSkills.languages,
    ...analysis.extractedSkills.web,
    ...analysis.extractedSkills.data,
    ...analysis.extractedSkills.cloudDevOps,
    ...analysis.extractedSkills.testing,
  ];

  const confidenceMap = analysis.skillConfidenceMap || {};
  const knownSkills = skills.filter(s => confidenceMap[s] === 'know');
  const practiceSkills = skills.filter(s => confidenceMap[s] !== 'know');

  return `
========================================
PLACEMENT PREPARATION REPORT
========================================

Company: ${analysis.company}
Role: ${analysis.role}
Date: ${new Date(analysis.createdAt).toLocaleDateString()}
Readiness Score: ${analysis.readinessScore}/100

----------------------------------------
SKILLS ASSESSMENT
----------------------------------------

Extracted Skills (${skills.length}):
${skills.map(s => `  • ${s} ${confidenceMap[s] === 'know' ? '✓' : '(needs practice)'}`).join('\n')}

Known Skills (${knownSkills.length}):
${knownSkills.length > 0 ? knownSkills.map(s => `  ✓ ${s}`).join('\n') : '  None marked as known'}

Skills Needing Practice (${practiceSkills.length}):
${practiceSkills.length > 0 ? practiceSkills.map(s => `  ○ ${s}`).join('\n') : '  All skills marked as known!'}

----------------------------------------
7-DAY PREPARATION PLAN
----------------------------------------

${formatPlanAsText(analysis.plan)}

----------------------------------------
ROUND-WISE CHECKLIST
----------------------------------------

${formatChecklistAsText(analysis.checklist)}

----------------------------------------
LIKELY INTERVIEW QUESTIONS
----------------------------------------

${formatQuestionsAsText(analysis.questions)}

----------------------------------------
END OF REPORT
----------------------------------------
Generated by Placement Prep Platform
`.trim();
}

export function downloadAsTxt(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
